services:
  bae-vit:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models
      - ./test_images:/app/test_images   # ojo: tu carpeta se llama "test_images", no "test-images"
      - ./configs:/app/configs:ro        # ⬅️ monta configs de solo lectura
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
